baseurl = "http://www.fulcircle.io" # Hostname (and path) to the root.
title = "Vik Sunkavalli" # Site title.
theme = "coder-plus" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Vik Sunkavalli" # Author's name.
    info = "Full-stack Developer" # Author's job title or info.
    description = "Vik Sunkavalli's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/avatar-bw.png" # Contain the path of the optionnal avatar in the static folder.

    headerContent = false
    footercontent = "" # Add footer content
    fixedbarContent = "" # Add fixedbar content
    fixedbarContentAfter = "" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

    showprojects = true

# Menu links
[[menu.main]]
    name = "Posts"
    weight = 1
    url  = "posts"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true